version: '3'
services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy-balanceador
    ports:
      - "80:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    restart: unless-stopped